[project]
name = "Token Management System"
description = "A token management system on Stacks blockchain"
authors = ["Your Name <your.email@example.com>"]
telemetry = true
cache_dir = "./.clarinet"

[contracts.bootcamp-token-v3]
path = "contracts/bootcamp-token-v3.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2